# Generated by Django 5.0.3 on 2024-10-11 13:57

from django.db import migrations, models


def create_default_durations(apps, schema_editor):
    Duration = apps.get_model('settings', 'Duration')
    durations = [{
            'time': 20,
            'is_default': False,
        },
        {
            'time': 30,
            'is_default': False,
        },
        {
            'time': 40,
            'is_default': False,
        },
        {
            'time': 45,
            'is_default': False,
        },
        {
            'time': 60,
            'is_default': True,
        },
        {
            'time': 75,
            'is_default': False,
        },
        {
            'time': 90,
            'is_default': False,
        }]
    for time in durations:
        Duration.objects.get_or_create(time=time['time'], is_default=time['is_default'])


def create_default_language(apps, schema_editor):
    Language = apps.get_model('settings', 'Language')
    names = ['English']
    for name in names:
        Language.objects.get_or_create(name=name)


def create_default_currency(apps, schema_editor):
    Currency = apps.get_model('settings', 'Currency')
    currencies = [{
        'name': 'USD',
        'symbol': '$',
        'exchange': 1.0,
        'is_default': True,
    }]
    for currency in currencies:
        Currency.objects.get_or_create(name=currency['name'], symbol=currency['symbol'], exchange=currency['exchange'],
                                       is_default=currency['is_default'])


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True, verbose_name='name')),
                ('symbol', models.CharField(blank=True, max_length=3, null=True, verbose_name='symbol')),
                ('exchange', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='exchange')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.RunPython(create_default_currency),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(unique=True, verbose_name='time')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Duration',
                'verbose_name_plural': 'Durations',
                'ordering': ['time'],
            },
        ),
        migrations.RunPython(create_default_durations),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.RunPython(create_default_language),
    ]
