# Generated by Django 5.0.3 on 2024-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='duration',
            options={'verbose_name': 'Duration', 'verbose_name_plural': 'Durations'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=3, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='symbol'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='time',
            field=models.IntegerField(unique=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
