# Generated by Django 5.0.3 on 2024-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_currency_options_alter_duration_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='default',
            new_name='is_default',
        ),
        migrations.AddField(
            model_name='duration',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
