# Generated by Django 5.0.3 on 2024-10-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_default_currency_is_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duration',
            options={'ordering': ['time'], 'verbose_name': 'Duration', 'verbose_name_plural': 'Durations'},
        ),
    ]
