# Generated by Django 5.0.3 on 2024-10-11 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def create_default_category(apps, schema_editor):
    CategoryPlan = apps.get_model('pricing', 'CategoryPlan')
    categories = ['default']
    for category in categories:
        CategoryPlan.objects.get_or_create(
            title=category,
        )

def create_default_plan(apps, schema_editor):
    Plan = apps.get_model('pricing', 'Plan')
    CategoryPlan = apps.get_model('pricing', 'CategoryPlan')  # Модель для category
    Currency = apps.get_model('settings', 'Currency')  # Модель для currency (если это другая модель)

    # Получаем экземпляры связанных объектов по их ID
    default_category = CategoryPlan.objects.get(id=1)
    default_currency = Currency.objects.get(id=1)
    plans = [{
        'title': 'Default',
        'description': 'Default plan',
        'price': '20',
        'period_type': 'hour',
        'period_duration': '1',
        'discount': '0',
        'discount_date_end': None,
        'category': default_category,
        'currency': default_currency,
    }]
    for plan in plans:
        Plan.objects.get_or_create(
            title=plan['title'],
            description=plan['description'],
            price=plan['price'],
            period_type=plan['period_type'],
            period_duration=plan['period_duration'],
            discount=plan['discount'],
            discount_date_end=plan['discount_date_end'],
            category=plan['category'],
            currency=plan['currency'],
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('period_type', models.CharField(choices=[('hour', 'Hour')], default='hour', max_length=50, verbose_name='period type')),
                ('period_duration', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, "Can't be less 1")], verbose_name='period duration')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, "Discount can't be less than 0."), django.core.validators.MaxValueValidator(100, "Discount can't be greater than 100.")])),
                ('discount_date_end', models.DateField(blank=True, default=None, null=True, verbose_name='discount date end')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.categoryplan')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency', verbose_name='currency')),
            ],
        ),
        migrations.RunPython(create_default_category),
        migrations.RunPython(create_default_plan),
    ]
