# Generated by Django 5.0.3 on 2024-10-11 13:57

from django.db import migrations, models

def create_default_pages(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    pages = [{
        'title': 'Privacy Policy',
        'slug': 'privacy-policy',
        'content': 'Add your policy',
        'status': 'published',
    },
    {
        'title': 'Terms & Conditions',
        'slug': 'terms-conditions',
        'content': 'Add your terms',
        'status': 'published',
    }]
    for page in pages:
        Page.objects.get_or_create(
            title_en=page['title'],
            slug=page['slug'],
            content_en=page['content'],
            status=page['status'],
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('content_en', models.TextField(null=True, verbose_name='content')),
                ('content_ru', models.TextField(null=True, verbose_name='content')),
                ('content_uk', models.TextField(null=True, verbose_name='content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.RunPython(create_default_pages),
    ]
