# Generated by Django 5.0.3 on 2024-09-22 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_pages(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    pages = [{
        'title': 'Privacy Policy',
        'slug': 'privacy-policy',
        'content': 'Add your policy',
        'status': 'published',
    },
    {
        'title': 'Terms & Conditions',
        'slug': 'terms-conditions',
        'content': 'Add your terms',
        'status': 'published',
    }]
    for page in pages:
        Page.objects.get_or_create(
            title='Privacy Policy',
            slug='privacy-policy',
            content='Add your policy',
            status='published',
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_default_pages),
    ]
