# Generated by Django 5.0.3 on 2024-10-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_content_en_page_content_ru_page_content_uk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content_uk',
            new_name='content_ua',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_uk',
            new_name='title_ua',
        ),
    ]
