# Generated by Django 5.0.3 on 2024-10-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_content_uk_page_content_ua_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content_ua',
            new_name='content_uk',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title_ua',
            new_name='title_uk',
        ),
    ]
