# Generated by Django 5.0.3 on 2024-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.ManyToManyField(to='settings.language'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='language',
            field=models.ManyToManyField(to='settings.language'),
        ),
    ]
