# Generated by Django 5.0.3 on 2024-03-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_language_teacher_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='language',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
