# Generated by Django 5.0.3 on 2024-09-21 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency'),
        ),
    ]
