# Generated by Django 5.0.3 on 2024-09-28 18:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options_alter_company_currency_and_more'),
        ('school', '0004_alter_lesson_time'),
        ('settings', '0002_alter_currency_options_alter_duration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'verbose_name': 'Student Progress', 'verbose_name_plural': 'Student Progresses'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.duration', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='homework'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('conducted', 'Conducted'), ('missed', 'Missed')], default='planned', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(to='school.student', verbose_name='students'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theme',
            field=models.CharField(max_length=255, verbose_name='theme'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='student',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.ManyToManyField(to='settings.language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='school.teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='wallet'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.ManyToManyField(to='settings.language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
