# Generated by Django 5.0.3 on 2024-03-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='wallet',
        ),
    ]
