# Generated by Django 5.0.3 on 2024-10-08 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_lesson_options_alter_studentprogress_options_and_more'),
        ('transactions', '0011_categoryprice_price_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='price_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.price', verbose_name='price'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='price_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.price', verbose_name='price'),
        ),
    ]
