# Generated by Django 5.0.3 on 2024-10-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student_price_plan_teacher_price_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rate',
        ),
    ]
