# Generated by Django 5.0.3 on 2024-03-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_student_teacher_delete_abstractschoolprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='student',
            name='language',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
