# Generated by Django 5.0.3 on 2024-04-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_student_created_at_teacher_created_at_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonteacherprice',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonteacherprice',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='LessonStudentPrice',
        ),
        migrations.DeleteModel(
            name='LessonTeacherPrice',
        ),
    ]
