# Generated by Django 5.0.3 on 2024-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_lessonteacherprice_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('сonducted', 'Conducted'), ('missed', 'Missed')], default='planned', max_length=50),
        ),
    ]
