# Generated by Django 5.0.3 on 2024-04-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_lesson_status'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency'),
        ),
    ]
