# Generated by Django 5.0.3 on 2024-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_studentprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
