# Generated by Django 5.0.3 on 2024-09-29 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_page_content_en_page_content_ru_page_content_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='tagline')),
                ('logo_icon', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='logo_icon')),
                ('logo_full', models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='logo_full')),
                ('phone1', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('phone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='FooterMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page')),
            ],
            options={
                'verbose_name': 'Footer Menu Item',
                'verbose_name_plural': 'Footer Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
