# Generated by Django 5.0.3 on 2024-09-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.DeleteModel(
            name='FooterMenuItem',
        ),
    ]
