# Generated by Django 5.0.3 on 2024-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_alter_siteinfo_options_delete_footermenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo_text',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='logo_text'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo_full',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='logo_full'),
        ),
    ]
