# Generated by Django 5.0.3 on 2024-10-11 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_default_transactions_types(apps, schema_editor):
    TransactionType = apps.get_model('transactions', 'TransactionType')
    types = [{
            'title': 'Outgoing lesson transaction',
            'title_en': 'Outgoing lesson transaction',
            'description': 'Automatic created outgoing transaction for lesson',
            'description_en': 'Automatic created outgoing transaction for lesson',
            'type': '-',
            'is_system': True,
        },
        {
            'title': 'Incoming lesson transaction',
            'title_en': 'Incoming lesson transaction',
            'description': 'Automatic created incoming transaction for lesson',
            'description_en': 'Automatic created incoming transaction for lesson',
            'type': '+',
            'is_system': True,
        }]
    for type in types:
        TransactionType.objects.get_or_create(
            title=type['title'],
            title_en=type['title_en'],
            description=type['description'],
            description_en=type['description_en'],
            type=type['type'],
            is_system=type['is_system'],
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('description_uk', models.TextField(null=True, verbose_name='description')),
                ('type',
                 models.CharField(choices=[('+', 'Incoming transaction'), ('-', 'Outgoing transaction')], default='+',
                                  max_length=50, verbose_name='type')),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
            },
        ),
        migrations.RunPython(create_default_transactions_types),
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='school.lesson', verbose_name='lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher',
                                              verbose_name='teacher')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                       to='transactions.transactiontype',
                                                       verbose_name='transaction type')),
            ],
            options={
                'verbose_name': 'Teacher Payment',
                'verbose_name_plural': 'Teachers Payment',
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='school.lesson', verbose_name='lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student',
                                              verbose_name='student')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                       to='transactions.transactiontype',
                                                       verbose_name='transaction type')),
            ],
            options={
                'verbose_name': 'Student Payment',
                'verbose_name_plural': 'Students Payment',
            },
        ),
        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company',
                                              verbose_name='company')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='school.lesson', verbose_name='lesson')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                       to='transactions.transactiontype',
                                                       verbose_name='transaction type')),
            ],
            options={
                'verbose_name': 'Company Payment',
                'verbose_name_plural': 'Companies Payment',
            },
        ),
    ]
