# Generated by Django 5.0.3 on 2024-04-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonstudentprice',
            old_name='students',
            new_name='student',
        ),
        migrations.AddField(
            model_name='lessoncompanyprice',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessonstudentprice',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessonteacherprice',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
