# Generated by Django 5.0.3 on 2024-04-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('school', '0013_lesson_currency'),
        ('transactions', '0002_rename_students_lessonstudentprice_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonCompanyPrice',
            new_name='TransactionLessonCompanyPrice',
        ),
        migrations.RenameModel(
            old_name='LessonStudentPrice',
            new_name='TransactionLessonStudentPrice',
        ),
        migrations.RenameModel(
            old_name='LessonTeacherPrice',
            new_name='TransactionLessonTeacherPrice',
        ),
    ]
