# Generated by Django 5.0.3 on 2024-09-28 18:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options_alter_company_currency_and_more'),
        ('school', '0005_alter_lesson_options_alter_studentprogress_options_and_more'),
        ('transactions', '0002_alter_companypayment_lesson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypayment',
            options={'verbose_name': 'Company Payment', 'verbose_name_plural': 'Companies Payment'},
        ),
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'verbose_name': 'Student Payment', 'verbose_name_plural': 'Students Payment'},
        ),
        migrations.AlterModelOptions(
            name='teacherpayment',
            options={'verbose_name': 'Teacher Payment', 'verbose_name_plural': 'Teachers Payment'},
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.lesson', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.lesson', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.lesson', verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher', verbose_name='teacher'),
        ),
    ]
