# Generated by Django 5.0.3 on 2024-10-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_companypayment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('incoming', 'Incoming transaction'), ('outgoing', 'Outgoing transaction')], default='incoming', max_length=50, verbose_name='type')),
                ('is_system', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='companypayment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teacherpayment',
            name='description',
        ),
        migrations.AddField(
            model_name='companypayment',
            name='transaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactiontype', verbose_name='transaction type'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='transaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactiontype', verbose_name='transaction type'),
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='transaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactiontype', verbose_name='transaction type'),
        ),
    ]
