# Generated by Django 5.0.3 on 2024-05-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('school', '0013_lesson_currency'),
        ('transactions', '0003_rename_lessoncompanyprice_transactionlessoncompanyprice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionLessonCompanyPrice',
            new_name='CompanyPayment',
        ),
        migrations.RenameModel(
            old_name='TransactionLessonTeacherPrice',
            new_name='StudentPayment',
        ),
        migrations.RenameModel(
            old_name='TransactionLessonStudentPrice',
            new_name='TeacherPayment',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherpayment',
            name='student',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
            preserve_default=False,
        ),
    ]
