# Generated by Django 5.0.3 on 2024-05-09 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_transactionlessoncompanyprice_companypayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypayment',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
