# Generated by Django 5.0.3 on 2024-10-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactiontype_remove_companypayment_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'verbose_name': 'Transaction Type', 'verbose_name_plural': 'Transaction Types'},
        ),
    ]
