# Generated by Django 5.0.3 on 2024-10-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transactiontype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
