# Generated by Django 5.0.3 on 2024-10-07 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactiontype_description_transactiontype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypayment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created at'),
        ),
    ]
