# Generated by Django 5.0.3 on 2024-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_companypayment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
