# Generated by Django 5.0.3 on 2024-10-07 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_currency_options_alter_duration_options_and_more'),
        ('transactions', '0008_transactiontype_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(max_length=255, verbose_name='title')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('period_type', models.CharField(choices=[('hour', 'Hour'), ('month', 'Month')], default='hour', max_length=50, verbose_name='period type')),
                ('period_duration', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, "Can't be less 1")], verbose_name='period duration')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, "Discount can't be less than 0."), django.core.validators.MaxValueValidator(100, "Discount can't be greater than 100.")])),
                ('discount_date_end', models.DateField(blank=True, default=None, null=True, verbose_name='discount date end')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency', verbose_name='currency')),
            ],
        ),
    ]
