# Generated by Django 5.0.3 on 2024-10-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
