# Generated by Django 5.0.3 on 2024-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_categoryprice_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='type',
            field=models.CharField(choices=[('+', 'Incoming transaction'), ('-', 'Outgoing transaction')], default='+', max_length=50, verbose_name='type'),
        ),
    ]
