# Generated by Django 5.0.3 on 2024-10-11 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transactiontype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='price',
            name='period_type',
            field=models.CharField(choices=[('hour', 'Hour')], default='hour', max_length=50, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
