# Generated by Django 5.0.3 on 2024-10-11 13:57

import django.db.models.deletion
from django.db import migrations, models


def create_default_category(apps, schema_editor):
    Category = apps.get_model('faq', 'Category')
    categories = ['Uncategorized']
    for category in categories:
        Category.objects.get_or_create(title_en=category)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(create_default_category),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='question')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='question')),
                ('question_uk', models.CharField(max_length=255, null=True, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_en', models.TextField(null=True, verbose_name='answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='answer')),
                ('answer_uk', models.TextField(null=True, verbose_name='answer')),
                ('category',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faq.category',
                                   verbose_name='category')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
