# Generated by Django 5.0.3 on 2024-09-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_category_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_uk',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='question'),
        ),
    ]
