# Generated by Django 5.0.3 on 2024-10-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_category_title_en_category_title_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_uk',
            new_name='title_ua',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_uk',
            new_name='answer_ua',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_uk',
            new_name='question_ua',
        ),
    ]
