# Generated by Django 5.0.3 on 2024-10-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_rename_title_uk_category_title_ua_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_ua',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_ua',
            new_name='answer_uk',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_ua',
            new_name='question_uk',
        ),
    ]
