# Generated by Django 5.0.3 on 2024-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_role',
            field=models.CharField(choices=[('None', 'None'), ('teacher', 'Teacher'), ('student', 'Student')], default='None', max_length=10, verbose_name='School role'),
        ),
    ]
