# Generated by Django 5.0.3 on 2024-10-11 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name')),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='wallet')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, "Discount can't be less than 0."), django.core.validators.MaxValueValidator(100, "Discount can't be greater than 100.")])),
                ('is_active', models.BooleanField(default=True)),
                ('price_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.plan', verbose_name='price')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
