# Generated by Django 5.0.3 on 2024-09-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_is_active'),
        ('settings', '0002_alter_currency_options_alter_duration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='wallet'),
        ),
    ]
