# Generated by Django 5.0.3 on 2024-10-07 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options_alter_company_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, "Discount can't be less than 0."), django.core.validators.MaxValueValidator(100, "Discount can't be greater than 100.")]),
        ),
    ]
