# Generated by Django 5.0.3 on 2024-10-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_price_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rate',
        ),
    ]
